### ISSUE TITLE
paired_distances() takes 2 positional arguments

### ISSUE THREAD

**Issue by Mewgia** [ericcombiolab/Pangaea#1]
Hello!

I'm trying to use Pangaea with test data and have the following problem:
Traceback (most recent call last):
  File "/home/yana/Pangaea/pangaea.py", line 86, in <module>
    main()
  File "/home/yana/Pangaea/pangaea.py", line 81, in main
    run(args, script_path)
  File "/home/yana/Pangaea/pangaea.py", line 42, in run
    labels, barcodes = model.train(dataloader_train, dataloader_test, dataloader_original, args.output, args.patience)
  File "/home/yana/Pangaea/models/VAENET.py", line 136, in train
    labels = clustering_rph_kmeans(embedding, self.num_classes)
  File "/home/yana/Pangaea/clustering.py", line 14, in clustering_rph_kmeans
    clusters = clt.fit_predict(embedding)
  File "/home/yana/miniconda3/lib/python3.9/site-packages/rph_kmeans/rph_kmeans_.py", line 139, in fit_predict
    self.fit(X)
  File "/home/yana/miniconda3/lib/python3.9/site-packages/rph_kmeans/rph_kmeans_.py", line 153, in fit
    init_centers_, reduced_X_, reduced_X_weight_, rp_labels_, rp_iter_, rp_inertia_, rp_y_pred_ = self.init_centers(X)
  File "/home/yana/miniconda3/lib/python3.9/site-packages/rph_kmeans/rph_kmeans_.py", line 117, in init_centers
    reduced_X, group_weight, labels, rp_iter = self.point_reducer.fit_transform(X)
  File "/home/yana/miniconda3/lib/python3.9/site-packages/rph_kmeans/point_reducer_cy.py", line 39, in fit_transform
    self.get_w(X)
  File "/home/yana/miniconda3/lib/python3.9/site-packages/rph_kmeans/utils.py", line 15, in wrapper
    coll = func(cls, *args, **kwargs)
  File "/home/yana/miniconda3/lib/python3.9/site-packages/rph_kmeans/point_reducer_base.py", line 46, in get_w
    sample_dist = self.get_sample_dist(X)
  File "/home/yana/miniconda3/lib/python3.9/site-packages/rph_kmeans/utils.py", line 15, in wrapper
    coll = func(cls, *args, **kwargs)
  File "/home/yana/miniconda3/lib/python3.9/site-packages/rph_kmeans/point_reducer_base.py", line 37, in get_sample_dist
    return paired_distances(
TypeError: paired_distances() takes 2 positional arguments but 3 were given

Command:

python /home/yana/Pangaea/pangaea.py \
-1 /home/yana/Pang_test/reads1.fq.gz \
-2 /home/yana/Pang_test/reads2.fq.gz \
-sp /home/yana/Pang_test/contigs.fa \
-lc /home/yana/Pang_test/flye-input-contigs.fa \
-at /home/yana/Pang_test/athena.asm.fa \
-c 5 -o /home/yana/Pang_test/pangaea

it's toy set from your example. Log is in the file attached.
[log.txt](https://github.com/ericcombiolab/Pangaea/files/11275124/log.txt)

What should i do?
Thank you.

**Comment by ZhangZhenmiao** [comment]
Hello!

This is because the rph_kmeans package is currently incompatible with higher versions of Python or scikit-learn. There is a simple temporary solution:

Delete the third parameter 'euclidean' (line 40) for function paired_distances in line 37 in your file /home/yana/miniconda3/lib/python3.9/site-packages/rph_kmeans/point_reducer_base.py.

And this will not change the performance, because [paired_distances](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.pairwise.paired_distances.html) uses Euclidean by default.

We will address this issue in our next release.

Thank you!
Zhenmiao

**Comment by Mewgia** [comment]
Zhenmiao, thanks a lot. Since my question, i've reinstalled all the components and Pangaea at all. And i don't know why, but now rph_kmeans is associated with python 3.7, not python 3.9. I've done all according to your advice: found the file and edited it, and at this stage all works great, but later...

2023-04-22 21:34:40 (INFO): command started: /home/yana/Pangaea/bin/extract_reads -1 /home/yana/Pang_test/reads1.fq.gz -2 /home/yana/Pang_test/reads2.fq.gz -c /home/yana/Pang_test/pangaea/3.clustering/clusters.tsv -o /home/yana/Pang_test/pangaea/3.clustering/cluster
2023-04-22 21:34:43 (INFO): command completed: /home/yana/Pangaea/bin/extract_reads -1 /home/yana/Pang_test/reads1.fq.gz -2 /home/yana/Pang_test/reads2.fq.gz -c /home/yana/Pang_test/pangaea/3.clustering/clusters.tsv -o /home/yana/Pang_test/pangaea/3.clustering/cluster
2023-04-22 21:34:43 (INFO): mapping reads to contigs
2023-04-22 21:34:43 (INFO): command started: /home/yana/Pangaea/bin/bin_assembly.sh /home/yana/Pang_test/pangaea/3.clustering /home/yana/Pang_test/pangaea/4.assembly /home/yana/Pang_test/reads1.fq.gz /home/yana/Pang_test/reads2.fq.gz 100
Traceback (most recent call last):
  File "/home/yana/Pangaea/pangaea.py", line 86, in <module>
    main()
  File "/home/yana/Pangaea/pangaea.py", line 81, in main
    run(args, script_path)
  File "/home/yana/Pangaea/pangaea.py", line 43, in run
    save_clustering_result(args.output, args.reads1, args.reads2, args.spades, args.local_assembly, args.athena, args.low_abd_cut, labels, barcodes, args.threads, script_path)
  File "/home/yana/Pangaea/clustering.py", line 47, in save_clustering_result
    run_cmd([bin_assembly, cluster_dir, assembly_dir, reads1, reads2, str(threads)])
  File "/home/yana/Pangaea/utils.py", line 57, in run_cmd
    ret = subprocess.run(command, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
  File "/home/yana/.pyenv/versions/3.7.12/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/yana/.pyenv/versions/3.7.12/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/home/yana/.pyenv/versions/3.7.12/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/yana/Pangaea/bin/bin_assembly.sh'

**Comment by ZhangZhenmiao** [comment]
Hello,

Thank you for using it. All the scripts under /home/yana/Pangaea/bin directory should be executable. This command "chmod +x -R /home/yana/Pangaea/bin/" should solve the problem.

Best regards,
Zhenmiao

**Comment by ZhangZhenmiao** [comment]
Hello,

Sorry for the inconvenience. You will also need to make sure the dependencies of Lathe are available in your environment, including [flye](https://github.com/fenderglass/Flye), [minimap2](https://github.com/lh3/minimap2), and the programs under MUMmer3.23 folder (should compile first, generating nucmer, delta-filter, and show-coords) of [quickmerge](https://github.com/mahulchak/quickmerge/tree/master/MUMmer3.23) (/path/to/quickmerge/MUMmer3.23/). We will use conda to install all the dependencies in our next release.

Best regards,
Zhenmiao

**Comment by Mewgia** [comment]
Hello again!
Thank you a lot for your help. I didnt think that there will be so many questions on my part, and very sorry for it. Now we have this:

2023-04-23 12:57:12 (INFO): tnf shape (5856, 136)
2023-04-23 12:57:12 (INFO): abundance shape (5856, 400)
2023-04-23 12:57:12 (INFO): calculate sampling weights
2023-04-23 12:57:12 (INFO): normalize data
2023-04-23 12:57:12 (INFO): preprocessing completed
/home/yana/.pyenv/versions/3.7.12/lib/python3.7/site-packages/torch/utils/data/dataloader.py:557: UserWarning: This DataLoader will create 100 worker processes in total. Our suggested max number of worker in current system is 12, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
2023-04-23 12:57:12 (INFO): trainning model already saved
Note: w of RPH is automatically set to 1.2332983016967773
2023-04-23 12:57:27 (INFO): mapping reads to contigs
2023-04-23 12:57:27 (INFO): command started: /home/yana/Pangaea/bin/bin_assembly.sh /home/yana/Pang_test/pangaea/3.clustering /home/yana/Pang_test/pangaea/4.assembly /home/yana/Pang_test/reads1.fq.gz /home/yana/Pang_test/reads2.fq.gz 100
2023-04-23 12:58:12 (ERROR): command failed: /home/yana/Pangaea/bin/bin_assembly.sh /home/yana/Pang_test/pangaea/3.clustering /home/yana/Pang_test/pangaea/4.assembly /home/yana/Pang_test/reads1.fq.gz /home/yana/Pang_test/reads2.fq.gz 100

flye, quickmerge (and MUMmer) and minimap are successfully installed.

**Comment by ZhangZhenmiao** [comment]
Hello,

What's the log if you run the command "/home/yana/Pangaea/bin/bin_assembly.sh /home/yana/Pang_test/pangaea/3.clustering /home/yana/Pang_test/pangaea/4.assembly /home/yana/Pang_test/reads1.fq.gz /home/yana/Pang_test/reads2.fq.gz 100" separately?

Best regards,
Zhenmiao

**Comment by Mewgia** [comment]
Thank you for your help!
2023-04-24 12:23:42 (INFO): command started: /home/yana/Pangaea/bin/merge_asm.sh /home/yana/Pang_test/pangaea/3.clustering /home/yana/Pang_test/pangaea/4.assembly /home/yana/Pang_test/flye-input-contigs.fa /home/yana/Pang_test/athena.asm.fa /home/yana/Pang_test/contigs.fa /home/yana/Pangaea/bin/Lathe/Snakefile
2023-04-24 12:24:04 (INFO): command completed: /home/yana/Pangaea/bin/merge_asm.sh /home/yana/Pang_test/pangaea/3.clustering /home/yana/Pang_test/pangaea/4.assembly /home/yana/Pang_test/flye-input-contigs.fa /home/yana/Pang_test/athena.asm.fa /home/yana/Pang_test/contigs.fa /home/yana/Pangaea/bin/Lathe/Snakefile
2023-04-24 12:24:04 (INFO): program finished successfully

I've reinstalled bwa and corrected this error:
merge_wrapper.py: error: the following arguments are required: -l/--length_cutoff
in quickmerge - i removed "required=True" for length_cutoff in /home/yana/quickmerge/merge_wrapper.py

**Comment by ZhangZhenmiao** [comment]
Thank you! Your feedback has been very helpful to us.
